name: Get Latest ESStatistikListeModtag File

on:
  workflow_call:
    outputs:
      hasFoundNewFile:
        description: "1 if a new file was found, otherwise 0"
        value: ${{ jobs.get-latest-esstatistiklistemodtag-file.outputs.hasFoundNewFile }}
  workflow_dispatch:

jobs:
  get-latest-esstatistiklistemodtag-file:
    runs-on: ubuntu-latest
    outputs:
      hasFoundNewFile: ${{ steps.get-latest-file.outputs.hasFoundNewFile }}
    steps:
      - name: Checkout ESStatistikListeParser-GitHub repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/ESStatistikListeParser-GitHub"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run GetLatestFile-GitHub script
        id: get-latest-file
        run: |
          python ${{ github.workspace }}/GetLatestFile-GitHub.py