name: Run Kid

on:
  workflow_call:
    inputs:
      previous-filename-no-suffix:
        description: 'Previous ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      filename-no-suffix:
        description: 'ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      discord-upload-limit:
        description: 'Discord Upload Limit (MiB)'
        required: true
        type: string
      github-upload-limit:
        description: 'GitHub Upload Limit (MiB)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      previous-filename-no-suffix:
        description: 'Previous ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      filename-no-suffix:
        description: 'ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      discord-upload-limit:
        description: 'Discord Upload Limit (MiB)'
        required: true
        type: string
      github-upload-limit:
        description: 'GitHub Upload Limit (MiB)'
        required: true
        type: string

jobs:
  run-kid:
    name: Run Kid
    runs-on: ubuntu-latest
    steps:
      - name: Display runner information
        run: |
          echo "cpu-core:       $(nproc --all)"
          echo "cpu-model:      $(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2- | sed 's/^[[:space:]]*//')"
          echo "hostname:       $(hostname)"
          echo "kernel-release: $(uname -r)"
          echo "kernel-version: $(uname -v)"
          echo "name:           $(grep '^NAME=' /etc/os-release | head -1 | cut -d= -f2- | tr -d '\"')"
          echo "platform:       $(uname -s)"
          echo "release:        $(grep '^VERSION_ID=' /etc/os-release | head -1 | cut -d= -f2- | tr -d '\"')"
          echo "total-memory:   $(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')"
          
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-haskell: "true"
          remove-codeql: "true"
          remove-swapfile: "true"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "AllanVester/ESStatistikListeParser-GitHub"
          ref: "main"
          path: "${{ github.workspace }}/"
          sparse-checkout: |
            /Branch-GitHub.py
            /go.mod
            /go.sum
            /Kid-GitHub.go
            /UploadToDiscord-GitHub.py
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Checkout ESStatistikListeModtag repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.filename-no-suffix }}"
          ref: "main"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Stitch ESStatistikListeModtag back together
        run: |
          cat ${{ github.workspace }}/temp/ESStatistikListeModtag/*.part* > "${{ github.workspace }}/${{ inputs.filename-no-suffix }}.zip"
          file "${{ github.workspace }}/${{ inputs.filename-no-suffix }}.zip"
          
          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout previous ESStatistikListeModtag repository (Kid-branch)
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.previous-filename-no-suffix }}"
          ref: "kid"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Stitch previous Kid-files back together
        run: |
          cat ${{ github.workspace }}/temp/ESStatistikListeModtag/*.part* > "${{ github.workspace }}/previouskid.json"
          file "${{ github.workspace }}/previouskid.json"
          
          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout ESStatistikListeModtag repository (Kid-branch)
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.filename-no-suffix }}"
          ref: "kid"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Set up Git
        working-directory: "${{ github.workspace }}/"
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global http.postBuffer 104857600

      - name: Set up Git for Kid-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          if git ls-remote --exit-code --heads origin ${{ inputs.filename-no-suffix }}.zip-kid; then
              echo "Branch already exists, deleting and recreating..."
              
              if git show-ref --verify --quiet refs/heads/${{ inputs.filename-no-suffix }}.zip-kid; then
                  git branch -D ${{ inputs.filename-no-suffix }}.zip-kid
              fi
              git push origin --delete ${{ inputs.filename-no-suffix }}.zip-kid
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-kid
          else
              echo "Branch does not exist, creating..."
              
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-kid
          fi

          git push -u origin ${{ inputs.filename-no-suffix }}.zip-kid

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Go dependencies
        run: |
          go mod tidy

      - name: Run Kid Go script
        run: |
          go run ${{ github.workspace }}/Kid-GitHub.go

      - name: Archive JSON-file (Kid)
        run: |
          mkdir -p ${{ github.workspace }}/kid-zip
          zip -j -r -s ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/kid-zip/${{ inputs.filename-no-suffix }}.json.zip ${{ github.workspace }}/kid.json

      - name: Archive JSON-file (NewKid)
        run: |
          mkdir -p ${{ github.workspace }}/newkid-zip
          zip -j -r -s ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/newkid-zip/${{ inputs.filename-no-suffix }}.json.zip ${{ github.workspace }}/newkid.json

      - name: Split JSON-file (Kid)
        run: |
          mkdir -p ${{ github.workspace }}/kid-split
          split -d -b ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/kid.json ${{ github.workspace }}/kid-split/${{ inputs.filename-no-suffix }}.json.part
          
      - name: Split JSON-file (NewKid)
        run: |
          mkdir -p ${{ github.workspace }}/newkid-split
          split -d -b ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/newkid.json ${{ github.workspace }}/newkid-split/${{ inputs.filename-no-suffix }}.json.part
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install pymongo discord-webhook

      - name: Upload JSON-file to GitHub Kid-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          mv ${{ github.workspace }}/kid.json ${{ github.workspace }}/temp/kid.json
          mv ${{ github.workspace }}/Branch-GitHub.py ${{ github.workspace }}/temp/Branch-GitHub.py
          
          python ${{ github.workspace }}/temp/Branch-GitHub.py kid
        env:
          FILENAME: "kid.json"
          FILENAME_NO_SUFFIX: "${{ inputs.filename-no-suffix }}"
          FILEPATH: "${{ github.workspace }}/temp/"
          BRANCHNAME: "${{ inputs.filename-no-suffix }}.zip-kid"
          GITHUB_UPLOAD_LIMIT: "${{ inputs.github-upload-limit }}"

      - name: Upload JSON-file to Discord Kid
        run: |
          python ${{ github.workspace }}/UploadToDiscord-GitHub.py kid
        env:
          FILENAME: "${{ inputs.filename-no-suffix }}.json"

      - name: Remove temp-directory
        run: |
          mv ${{ github.workspace }}/temp/Branch-GitHub.py ${{ github.workspace }}/Branch-GitHub.py
          
          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout ESStatistikListeModtag repository (NewKid-branch)
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.filename-no-suffix }}"
          ref: "newkid"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Set up Git for NewKid-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          if git ls-remote --exit-code --heads origin ${{ inputs.filename-no-suffix }}.zip-newkid; then
              echo "Branch already exists, deleting and recreating..."
              
              if git show-ref --verify --quiet refs/heads/${{ inputs.filename-no-suffix }}.zip-newkid; then
                  git branch -D ${{ inputs.filename-no-suffix }}.zip-newkid
              fi
              git push origin --delete ${{ inputs.filename-no-suffix }}.zip-newkid
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-newkid
          else
              echo "Branch does not exist, creating..."
              
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-newkid
          fi

          git push -u origin ${{ inputs.filename-no-suffix }}.zip-newkid

      - name: Upload JSON-file to GitHub NewKid-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          mv ${{ github.workspace }}/newkid.json ${{ github.workspace }}/temp/newkid.json
          mv ${{ github.workspace }}/Branch-GitHub.py ${{ github.workspace }}/temp/Branch-GitHub.py
          
          python ${{ github.workspace }}/temp/Branch-GitHub.py newkid
        env:
          FILENAME: "newkid.json"
          FILENAME_NO_SUFFIX: "${{ inputs.filename-no-suffix }}"
          FILEPATH: "${{ github.workspace }}/temp/"
          BRANCHNAME: "${{ inputs.filename-no-suffix }}.zip-newkid"
          GITHUB_UPLOAD_LIMIT: "${{ inputs.github-upload-limit }}"

      - name: Upload JSON-file to Discord NewKid
        run: |
          python ${{ github.workspace }}/UploadToDiscord-GitHub.py newkid
        env:
          FILENAME: "${{ inputs.filename-no-suffix }}.json"