name: Run Vin

on:
  workflow_call:
    inputs:
      previous-filename-no-suffix:
        description: 'Previous ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      filename-no-suffix:
        description: 'ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      discord-upload-limit:
        description: 'Discord Upload Limit (MiB)'
        required: true
        type: string
      github-upload-limit:
        description: 'GitHub Upload Limit (MiB)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      previous-filename-no-suffix:
        description: 'Previous ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      filename-no-suffix:
        description: 'ESStatistikListeModtag Filename (No Suffix)'
        required: true
        type: string
      discord-upload-limit:
        description: 'Discord Upload Limit (MiB)'
        required: true
        type: string
      github-upload-limit:
        description: 'GitHub Upload Limit (MiB)'
        required: true
        type: string

jobs:
  run-vin:
    name: Run Vin
    runs-on: ubuntu-latest
    steps:
      - name: Display runner information
        run: |
          echo "cpu-core:       $(nproc --all)"
          echo "cpu-model:      $(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2- | sed 's/^[[:space:]]*//')"
          echo "hostname:       $(hostname)"
          echo "kernel-release: $(uname -r)"
          echo "kernel-version: $(uname -v)"
          echo "name:           $(grep '^NAME=' /etc/os-release | head -1 | cut -d= -f2- | tr -d '\"')"
          echo "platform:       $(uname -s)"
          echo "release:        $(grep '^VERSION_ID=' /etc/os-release | head -1 | cut -d= -f2- | tr -d '\"')"
          echo "total-memory:   $(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')"
          
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-haskell: "true"
          remove-codeql: "true"
          remove-swapfile: "true"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "AllanVester/ESStatistikListeParser-GitHub"
          ref: "main"
          path: "${{ github.workspace }}/"
          sparse-checkout: |
            /Branch-GitHub.py
            /go.mod
            /go.sum
            /Vin-GitHub.go
            /UploadToDiscord-GitHub.py
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Checkout ESStatistikListeModtag repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.filename-no-suffix }}"
          ref: "main"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Stitch ESStatistikListeModtag back together
        run: |
          cat ${{ github.workspace }}/temp/ESStatistikListeModtag/*.part* > "${{ github.workspace }}/${{ inputs.filename-no-suffix }}.zip"
          file "${{ github.workspace }}/${{ inputs.filename-no-suffix }}.zip"
          
          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout previous ESStatistikListeModtag repository (Vin-branch)
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.previous-filename-no-suffix }}"
          ref: "vin"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Stitch previous Vin-files back together
        run: |
          cat ${{ github.workspace }}/temp/ESStatistikListeModtag/*.part* > "${{ github.workspace }}/previousvin.json"
          file "${{ github.workspace }}/previousvin.json"
          
          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout ESStatistikListeModtag repository (Vin-branch)
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.filename-no-suffix }}"
          ref: "vin"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Set up Git
        working-directory: "${{ github.workspace }}/"
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global http.postBuffer 104857600

      - name: Set up Git for Vin-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          if git ls-remote --exit-code --heads origin ${{ inputs.filename-no-suffix }}.zip-vin; then
              echo "Branch already exists, deleting and recreating..."
              
              if git show-ref --verify --quiet refs/heads/${{ inputs.filename-no-suffix }}.zip-vin; then
                  git branch -D ${{ inputs.filename-no-suffix }}.zip-vin
              fi
              git push origin --delete ${{ inputs.filename-no-suffix }}.zip-vin
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-vin
          else
              echo "Branch does not exist, creating..."
              
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-vin
          fi

          git push -u origin ${{ inputs.filename-no-suffix }}.zip-vin

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Go dependencies
        run: |
          go mod tidy

      - name: Run Vin Go script
        run: |
          go run ${{ github.workspace }}/Vin-GitHub.go

      - name: Archive JSON-file (Vin)
        run: |
          mkdir -p ${{ github.workspace }}/vin-zip
          zip -j -r -s ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/vin-zip/${{ inputs.filename-no-suffix }}.json.zip ${{ github.workspace }}/vin.json

      - name: Archive JSON-file (NewVin)
        run: |
          mkdir -p ${{ github.workspace }}/newvin-zip
          zip -j -r -s ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/newvin-zip/${{ inputs.filename-no-suffix }}.json.zip ${{ github.workspace }}/newvin.json

      - name: Split JSON-file (Vin)
        run: |
          mkdir -p ${{ github.workspace }}/vin-split
          split -d -b ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/vin.json ${{ github.workspace }}/vin-split/${{ inputs.filename-no-suffix }}.json.part
          
      - name: Split JSON-file (NewVin)
        run: |
          mkdir -p ${{ github.workspace }}/newvin-split
          split -d -b ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/newvin.json ${{ github.workspace }}/newvin-split/${{ inputs.filename-no-suffix }}.json.part

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install pymongo discord-webhook

      - name: Upload JSON-file to GitHub Vin-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          mv ${{ github.workspace }}/vin.json ${{ github.workspace }}/temp/vin.json
          mv ${{ github.workspace }}/Branch-GitHub.py ${{ github.workspace }}/temp/Branch-GitHub.py
          
          python ${{ github.workspace }}/temp/Branch-GitHub.py vin
        env:
          FILENAME: "vin.json"
          FILENAME_NO_SUFFIX: "${{ inputs.filename-no-suffix }}"
          FILEPATH: "${{ github.workspace }}/temp/"
          BRANCHNAME: "${{ inputs.filename-no-suffix }}.zip-vin"
          GITHUB_UPLOAD_LIMIT: "${{ inputs.github-upload-limit }}"

      - name: Upload JSON-file to Discord Vin
        run: |
          python ${{ github.workspace }}/UploadToDiscord-GitHub.py vin
        env:
          FILENAME: "${{ inputs.filename-no-suffix }}.json"

      - name: Remove temp-directory
        run: |
          mv ${{ github.workspace }}/temp/Branch-GitHub.py ${{ github.workspace }}/Branch-GitHub.py
          
          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout ESStatistikListeModtag repository (NewVin-branch)
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ inputs.filename-no-suffix }}"
          ref: "newvin"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            /ESStatistikListeModtag
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Set up Git for NewVin-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          if git ls-remote --exit-code --heads origin ${{ inputs.filename-no-suffix }}.zip-newvin; then
              echo "Branch already exists, deleting and recreating..."
              
              if git show-ref --verify --quiet refs/heads/${{ inputs.filename-no-suffix }}.zip-newvin; then
                  git branch -D ${{ inputs.filename-no-suffix }}.zip-newvin
              fi
              git push origin --delete ${{ inputs.filename-no-suffix }}.zip-newvin
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-newvin
          else
              echo "Branch does not exist, creating..."
              
              git checkout -b ${{ inputs.filename-no-suffix }}.zip-newvin
          fi

          git push -u origin ${{ inputs.filename-no-suffix }}.zip-newvin

      - name: Upload JSON-file to GitHub NewVin-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          mv ${{ github.workspace }}/newvin.json ${{ github.workspace }}/temp/newvin.json
          mv ${{ github.workspace }}/Branch-GitHub.py ${{ github.workspace }}/temp/Branch-GitHub.py
          
          python ${{ github.workspace }}/temp/Branch-GitHub.py newvin
        env:
          FILENAME: "newvin.json"
          FILENAME_NO_SUFFIX: "${{ inputs.filename-no-suffix }}"
          FILEPATH: "${{ github.workspace }}/temp/"
          REPOOWNER: "${{ github.repository_owner }}"
          BRANCHNAME: "${{ inputs.filename-no-suffix }}.zip-newvin"
          GITHUB_UPLOAD_LIMIT: "${{ inputs.github-upload-limit }}"

      - name: Upload JSON-file to Discord NewVin
        run: |
          python ${{ github.workspace }}/UploadToDiscord-GitHub.py newvin
        env:
          FILENAME: "${{ inputs.filename-no-suffix }}.json"